# Generated by Django 4.0.5 on 2022-06-30 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dafitnessapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fitness',
            new_name='dafitnessapp',
        ),
    ]
