# Generated by Django 4.0.5 on 2022-07-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dafitnessapp', '0003_data_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.FloatField(null=True)),
                ('lunch', models.FloatField(null=True)),
                ('dinner', models.FloatField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='q3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='q4',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='q5',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='q1',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='q2',
            field=models.FloatField(null=True),
        ),
    ]
