# Generated by Django 4.0.5 on 2022-07-01 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dafitnessapp', '0004_pie_data_date_created_data_q3_data_q4_data_q5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pie',
            name='snacks',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dafitnessapp.data')),
                ('pie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dafitnessapp.pie')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dafitnessapp.user')),
            ],
        ),
    ]
